#!/bin/zsh
mkdir user_code

mv Src/myMain.cpp user_code
mv Inc/myMain.hpp user_code


stm32pio generate

mv user_code/myMain.cpp Src/myMain.cpp
mv user_code/myMain.hpp Inc/myMain.hpp


rm -r user_code
mv Src/main.c Src/main.cpp
./injector.py Src/main.cpp
